# Generated by Django 5.2.8 on 2025-11-19 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("source", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordCloud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="source.source",
                        to_field="value",
                    ),
                ),
            ],
        ),
    ]
