# Generated by Django 5.2.8 on 2025-11-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotItem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotitem",
            name="url",
            field=models.URLField(default="https://example.com"),
            preserve_default=False,
        ),
    ]
