# Generated by Django 5.2.8 on 2025-11-15 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotItem", "0002_hotitem_url"),
        ("source", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotitem",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="source.source",
                to_field="value",
            ),
        ),
    ]
