# Generated by Django 5.2.8 on 2025-11-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotItem", "0003_alter_hotitem_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotitem",
            name="url",
            field=models.URLField(max_length=500),
        ),
    ]
