# Generated by Django 5.2.8 on 2025-11-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotItem", "0004_alter_hotitem_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotitem",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
